spring:
  profiles:
    active: http, oauth
  datasource:
    url: jdbc:h2:~/token
    schema: classpath:/schema.sql
    data: classpath:data.sql
  h2:
    console:
      enabled: true

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        exclude: '*'
