spring:
  profiles:
    active: https
  datasource:
    url: jdbc:h2:~/token
    schema: classpath:/schema.sql
    data: classpath:data.sql
  h2:
    console:
      enabled: true

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        exclude: '*'

security:
  jwt:
    key-store: classpath:iesikey.p12
    key-store-password: password
    key-pair-alias: iesi
    key-store-type: PKCS12
    key-pair-password: password