server:
  servlet:
    context-path: /api

iesi:
  home: .

spring:
  profiles:
    active: http
  datasource:
    url: jdbc:h2:~/token
    schema: classpath:schema.sql
    data: classpath:data.sql

management:
  endpoints:
    web:
      exposure:
        include: health, httptrace, metrics, mappings
  trace:
    http:
      include: request-headers,response-headers,cookie-headers,principal,time-taken,authorization-header,remote-address,session-id

security:
  jwt:
    key-store: classpath:iesikey.p12
    key-store-password: password
    key-pair-alias: iesi
    key-store-type: PKCS12
    key-pair-password: password

securitykey:
  jwt:
    public-key: classpath:public.txt