---
data:
  name: "fwk.setEnvironment"
  className: "io.metadew.iesi.script.action.fwk.FwkSetEnvironment"
  description: "Set the environment where the next steps will be executed on"
  parameters:
  - name: "environment"
    description: "Environment name where the next action will be executed on"
    type: "string"
    mandatory: "N"
    encrypted: "N"
    subroutine: ""
    impersonate: "N"
  status: "stable"
type: "ActionType"
