iesi:
  commandline:
    display:
      runtime:
        variable: N
  guard:
    authenticate: N
#  script:
#    execution:
#       runtime: ''
  server:
#    mode: off
    mode: standalone
    threads:
      size: 4
      timeout: 30
