server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        exclude: '*'
spring:
  datasource:
    url: jdbc:h2:~/cloud
    schema: classpath:/schema.sql
    data: classpath:data.sql
  application:
    name: SpringCloud
