server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: '*'
security:
  jwt:
    key-store: classpath:iesikey.p12
    key-store-type: PKCS12
    key-store-password: password
    key-pair-alias: iesi
    key-pair-password: password

spring:
#  application:
#    name: iesi-rest, iesi-admin
  datasource:
    url: jdbc:h2:~/token2
    schema: classpath:/schema.sql
    data: classpath:data.sql
  h2:
    console:
      enabled: false
  boot:
    admin:
      client:
        url: https://localhost:8081
        username: admin
        password: admin
        instance:
          name: IESI_REST
          metadata:
            user:
              name: admin
              password: admin
  profiles:
    active: https
