server:
  ssl:
    enabled: true
    key-alias: iesi6
    key-store: classpath:iesi6.p12
    key-store-type: PKCS12
    key-password: password
    key-store-password: password
  use-forward-headers: true

spring:
  boot:
    admin:
      client:
        instance:
          health-url: https://localhost:8080/api/actuator/health
          management-base-url: https://localhost:8080/api
          service-url: https://localhost:8080/api