spring:
  boot:
    admin:
      client:
        instance:
          health-url: http://localhost:8080/api/actuator/health
          management-base-url: http://localhost:8080/api
          service-url: http://localhost:8080/api