server:
  port: 8082
#spring:
#  application:
#      name: iesi-gateway, iesi-rest

security:
  jwt:
    public-key: classpath:public.txt

management:
  endpoints:
    web:
      exposure:
        exclude: '*'
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    environments:
      service-id: environments
      path: /api/environments/**
      url:  https://localhost:8080/api/environments

    connections:
      service-id: connections
      path: /api/connections/**
      url:  https://localhost:8080/api/connections

    components:
      service-id: components
      path: /api/components/**
      url:  https://localhost:8080/api/components

    impersonations:
      service-id: impersonations
      path: /api/impersonations/**
      url:  https://localhost:8080/api/impersonations

    scripts:
      service-id: scripts
      path: /api/scripts/**
      url:  https://localhost:8080/api/scripts

    spring-oauth-resource:
      service-id: oauth
      path: /api/oauth/token
      url: https://localhost:8080
spring:
  profiles:
    active: https
