server:
  ssl:
    enabled: true
    key-alias: iesi6
    key-store: classpath:iesi6.p12
    key-store-type: PKCS12
    key-password: password
    key-store-password: password
  use-forward-headers: true
