server:
  port: ${iesi-adminPort}

spring:
  boot:
    admin:
      ui:
        favicon: /assets/img/iesi.png
        favicon-danger: /assets/img/iesi.png
        title: IESI
        brand: <img src="assets/img/iesi.png"><span>IESI</span>
        public-url: ${iesi-adminFullUrl}
  application:
    name: iesi-admin
  aop:
    proxy-target-class: true
  security:
    user:
      name: ${iesi-adminUser}
      password: ${iesi-adminPassword}