server:
  ssl:
    enabled: true
    key-alias: iesi6
    key-password: password
    key-store: classpath:iesi6.p12
    key-store-password: password
    key-store-type: PKCS12

spring:
  boot:
    admin:
      ui:
        public-url: https://localhost:8081