---
data:
  name: "Environment"
  label: "Environments"
  description: "Design metadata for environments"
  type: "design"
  category: "connectivity"
  migrate: "Y"
  migrationKey: "NA"
type: "MetadataObject"
