server:
  port: 8080
  servlet:
    context-path: /api

spring.security.user:
  name: admin
  password: admin

security:
  jwt:
    key-store: classpath:francois.jks
    key-store-password: francois
    key-pair-alias: francois
    key-pair-password: francois
    
spring:
  application:
      name: IESI-REST
  boot:
    admin:
      client:
          url: http://localhost:8081/
          username: admin
          password: admin