server:
  port: 8080
  servlet:
    context-path: /api
spring.security.user:
  name: ${iesi-adminUser}
  password: ${iesi-adminPassword}

security:
  jwt:
    key-store: classpath:${iesi-security-keystore}
    key-store-password: ${iesi-security-keystore-password}
    key-pair-alias: ${iesi-security-keypair-alias}
    key-pair-password: ${iesi-security-keypair-password}
    #password est francois
spring:
  application:
    name: iesi-rest, iesi-admin, iesi-cloud
  boot:
    admin:
      client:
        url: http://localhost:8081/
        username: ${iesi-adminUser}
        password: ${iesi-adminPassword}